
clean:
	@rm -f *.o *.elf *.self *.470 *.bin *.map ../lv1/src/*.o ../debug/src/*.o ../lv2/src/*.o

all:
	@rm -f *.o *.elf *.self *.470 *.bin *.481c *.map ../lv1/src/*.o ../debug/src/*.o ../lv2/src/*.o
	@make -f Makefile_470C --no-print-directory

	@rm -f *.o *.elf *.470 *.470d *.map ../lv1/src/*.o ../debug/src/*.o ../lv2/src/*.o
	@make -f Makefile_470D --no-print-directory


