#ifndef __LV2_SYSCALL_H__
#define __LV2_SYSCALL_H__

#include <lv2/lv2.h>
#include <lv2/patch.h>

#define SYS_PROCESS_GETPID                                            1
#define SYS_PROCESS_WAIT_FOR_CHILD                                    2
#define SYS_PROCESS_EXIT											  3
#define SYS_PROCESS_GET_STATUS                                        4
#define SYS_PROCESS_DETACH_CHILD                                      5
#define SYS_PROCESS_CREATE_PROGRAM_SEGMENT						  	  6
#define SYS_PROCESS_DESTROY_PROGRAM_SEGMENT						  	  7
#define SYS_PROCESS_AUTHENTICATE_PROGRAM_SEGMENT					  8
#define SYS_PROCESS_LOAD_PROGRAM_SEGMENT							  9
#define SYS_PROCESS_UNLOAD_PROGRAM_SEGMENT						 	 10
#define SYS_PROCESS_FIND_PROGRAM_SEGMENT							 11
#define SYS_PROCESS_GET_NUMBER_OF_OBJECT                             12
#define SYS_PROCESS_GET_ID                                           13
#define SYS_PROCESS_IS_SPU_LOCK_LINE_RESERVATION_ADDRESS             14
#define SYS_PROCESS_CREATE										     15
#define SYS_PROCESS_CREATE_PRIMARY_PPU_THREAD						 17
#define SYS_PROCESS_GETPPID                                          18
#define SYS_PROCESS_KILL                                             19
#define SYS_PROCESS_CREATE_PRIMARY_PPU_THREAD_TLS					 20
#define SYS_PROCESS_SPAWN											 21
#define SYS_PROCESS_EXIT2											 22
#define SYS_PROCESS_WAIT_FOR_CHILD2                                  23
#define _SYS_PROCESS_SPAWN2										     24
#define SYS_PROCESS_GET_SDK_VERSION                                  25
#define _SYS_PROCESS_EXIT											 26 
#define _SYS_PROCESS_SPAWN3										 	 27 
#define _SYS_PROCESS_GET_NUMBER_OF_OBJECT							 28 
#define _SYS_PROCESS_GET_ID										 	 29
#define SYS_PROCESS_GET_PARAMSFO				     				 30
#define SYS_PROCESS_GET_PPU_GUID                                     31
#define SYS_PPU_THREAD_EXIT											 41
#define SYS_PPU_THREAD_GET_ID										 42
#define SYS_PPU_THREAD_YIELD                                         43
#define SYS_PPU_THREAD_JOIN                                          44
#define SYS_PPU_THREAD_DETACH                                        45
#define SYS_PPU_THREAD_GET_JOIN_STATE                                46
#define SYS_PPU_THREAD_SET_PRIORITY                                  47
#define SYS_PPU_THREAD_GET_PRIORITY                                  48
#define SYS_PPU_THREAD_GET_STACK_INFORMATION                         49
#define SYS_PPU_THREAD_STOP											 50
#define SYS_PPU_THREAD_RESTART										 51
#define SYS_PPU_THREAD_CREATE										 52
#define SYS_PPU_THREAD_START										 53
#define _GET_ALLOCATION_INFORMATION								 	 54
#define _SET_ALLOCATION_INFORMATION								 	 55
#define SYS_PPU_THREAD_RENAME                                        56
#define SYS_PPU_THREAD_RECOVER_PAGE_FAULT                            57
#define SYS_PPU_THREAD_GET_PAGE_FAULT_CONTEXT                        58
#define SYS_TRACE_CREATE											 60
#define SYS_TRACE_START												 61
#define SYS_TRACE_STOP												 62
#define SYS_TRACE_UPDATE_TOP_INDEX									 63
#define SYS_TRACE_DESTROY											 64
#define SYS_TRACE_DRAIN												 65
#define SYS_TRACE_ATTACH_PROCESS									 66
#define SYS_TRACE_ALLOCATE_BUFFER                                    67
#define SYS_TRACE_FREE_BUFFER                                        68
#define SYS_TRACE_CREATE2                                            69
#define SYS_TIMER_CREATE                                             70
#define SYS_TIMER_DESTROY                                            71
#define SYS_TIMER_GET_INFORMATION                                    72
#define _SYS_TIMER_START                                             73
#define SYS_TIMER_STOP                                               74
#define SYS_TIMER_CONNECT_EVENT_QUEUE                                75
#define SYS_TIMER_DISCONNECT_EVENT_QUEUE                             76
#define SYS_TRACE_CREATE2_IN_CBEPM                                   77
#define SYS_TRACE_													 78
#define SYS_INTERRUPT_TAG_CREATE                                     80
#define SYS_INTERRUPT_TAG_DESTROY                                    81
#define SYS_EVENT_FLAG_CREATE                                        82
#define SYS_EVENT_FLAG_DESTROY                                       83
#define _SYS_INTERRUPT_THREAD_ESTABLISH                              84
#define SYS_EVENT_FLAG_WAIT                                          85
#define SYS_EVENT_FLAG_TRYWAIT                                       86
#define SYS_EVENT_FLAG_SET                                           87
#define SYS_INTERRUPT_THREAD_EOI                                     88
#define _SYS_INTERRUPT_THREAD_DISESTABLISH                           89
#define SYS_SEMAPHORE_CREATE                                         90
#define SYS_SEMAPHORE_DESTROY                                        91
#define SYS_SEMAPHORE_WAIT                                           92
#define SYS_SEMAPHORE_TRYWAIT                                        93
#define SYS_SEMAPHORE_POST                                           94
#define SYS_LWMUTEX_CREATE											 95
#define SYS_LWMUTEX_DESTROY											 96
#define SYS_LWMUTEX_LOCK											 97
#define SYS_LWMUTEX_UNLOCK											 98
#define SYS_LWMUTEX_TRYLOCK											 99
#define SYS_MUTEX_CREATE                                            100
#define SYS_MUTEX_DESTROY                                           101
#define SYS_MUTEX_LOCK                                              102
#define SYS_MUTEX_TRYLOCK                                           103
#define SYS_MUTEX_UNLOCK                                            104
#define SYS_COND_CREATE                                             105
#define SYS_COND_DESTROY                                            106
#define SYS_COND_WAIT                                               107
#define SYS_COND_SIGNAL                                             108
#define SYS_COND_SIGNAL_ALL                                         109
#define SYS_COND_SIGNAL_TO                                          110
#define SYS_LWCOND_CREATE											111
#define SYS_LWCOND_DESTROY											112
#define SYS_LWCOND_QUEUE_WAIT										113
#define SYS_SEMAPHORE_GET_VALUE                                     114
#define SYS_LWCOND_SIGNAL											115
#define SYS_LWCOND_SIGNAL_ALL										116
#define SYS_LWMUTEX_UNLOCK2											117
#define SYS_EVENT_FLAG_CLEAR                                        118
#define SYS_TIME_GET_RTC											119
#define SYS_RWLOCK_CREATE                                           120
#define SYS_RWLOCK_DESTROY                                          121
#define SYS_RWLOCK_RLOCK                                            122
#define SYS_RWLOCK_TRYRLOCK                                         123
#define SYS_RWLOCK_RUNLOCK                                          124
#define SYS_RWLOCK_WLOCK                                            125
#define SYS_RWLOCK_TRYWLOCK											126
#define SYS_RWLOCK_WUNLOCK                                          127
#define SYS_EVENT_QUEUE_CREATE                                      128
#define SYS_EVENT_QUEUE_DESTROY                                     129
#define SYS_EVENT_QUEUE_RECEIVE                                     130
#define SYS_EVENT_QUEUE_TRYRECEIVE                                  131
#define SYS_EVENT_FLAG_CANCEL                                       132
#define SYS_EVENT_QUEUE_DRAIN                                       133
#define SYS_EVENT_PORT_CREATE                                       134
#define SYS_EVENT_PORT_DESTROY                                      135
#define SYS_EVENT_PORT_CONNECT_LOCAL                                136
#define SYS_EVENT_PORT_DISCONNECT                                   137
#define SYS_EVENT_PORT_SEND                                         138
#define SYS_EVENT_FLAG_GET                                          139
#define SYS_EVENT_PORT_CONNECT_IPC                                  140
#define SYS_TIMER_USLEEP                                            141
#define SYS_TIMER_SLEEP                                             142
#define SYS_TIME_SET_TIMEZONE										143
#define SYS_TIME_GET_TIMEZONE										144
#define SYS_TIME_GET_CURRENT_TIME                                   145
#define SYS_TIME_GET_TIMEBASE_FREQUENCY                             147
#define _SYS_RWLOCK_TRYWLOCK                                        148
#define SYS_RAW_SPU_CREATE_INTERRUPT_TAG                            150
#define SYS_RAW_SPU_SET_INT_MASK                                    151
#define SYS_RAW_SPU_GET_INT_MASK                                    152
#define SYS_RAW_SPU_SET_INT_STAT                                    153
#define SYS_RAW_SPU_GET_INT_STAT                                    154
#define SYS_SPU_IMAGE_GET_INFORMATION								155
#define SYS_SPU_IMAGE_OPEN                                          156
#define SYS_SPU_IMAGE_IMPORT										157
#define SYS_SPU_IMAGE_CLOSE											158
#define SYS_RAW_SPU_LOAD											159
#define SYS_RAW_SPU_CREATE                                          160
#define SYS_RAW_SPU_DESTROY                                         161
#define SYS_RAW_SPU_READ_PUINT_MB                                   163
#define SYS_SPU_THREAD_GET_EXIT_STATUS                              165
#define SYS_SPU_THREAD_SET_ARGUMENT                                 166
#define SYS_SPU_THREAD_GROUP_START_ON_EXIT                          167
#define SYS_SPU_INITIALIZE                                          169
#define SYS_SPU_THREAD_GROUP_CREATE                                 170
#define SYS_SPU_THREAD_GROUP_DESTROY                                171
#define SYS_SPU_THREAD_INITIALIZE                                   172
#define SYS_SPU_THREAD_GROUP_START                                  173
#define SYS_SPU_THREAD_GROUP_SUSPEND                                174
#define SYS_SPU_THREAD_GROUP_RESUME                                 175
#define SYS_SPU_THREAD_GROUP_YIELD                                  176
#define SYS_SPU_THREAD_GROUP_TERMINATE                              177
#define SYS_SPU_THREAD_GROUP_JOIN                                   178
#define SYS_SPU_THREAD_GROUP_SET_PRIORITY                           179
#define SYS_SPU_THREAD_GROUP_GET_PRIORITY                           180
#define SYS_SPU_THREAD_WRITE_LS                                     181
#define SYS_SPU_THREAD_READ_LS                                      182
#define SYS_SPU_THREAD_ENQUEUE_DMA									183
#define SYS_SPU_THREAD_WRITE_SNR                                    184
#define SYS_SPU_THREAD_GROUP_CONNECT_EVENT                          185
#define SYS_SPU_THREAD_GROUP_DISCONNECT_EVENT                       186
#define SYS_SPU_THREAD_SET_SPU_CFG                                  187
#define SYS_SPU_THREAD_GET_SPU_CFG                                  188
#define SYS_SPU_THREAD_READ_PU_MB									189
#define SYS_SPU_THREAD_WRITE_SPU_MB                                 190
#define SYS_SPU_THREAD_CONNECT_EVENT                                191
#define SYS_SPU_THREAD_DISCONNECT_EVENT                             192
#define SYS_SPU_THREAD_BIND_QUEUE                                   193
#define SYS_SPU_THREAD_UNBIND_QUEUE                                 194
#define SYS_RAW_SPU_SET_SPU_CFG                                     196
#define SYS_RAW_SPU_GET_SPU_CFG                                     197
#define SYS_SPU_THREAD_RECOVER_PAGE_FAULT                           198
#define SYS_RAW_SPU_RECOVER_PAGE_FAULT                              199
//#define (console_putc)											200
//#define (console_getc)											201
//#define (event_create_port)										202
//#define (event_send_locally)										203
//#define (sys_pseudo_fs_read)										209
//#define (sys_pseudo_fs_write)										210
//#define (sys_pseudo_fs_append)									211
//#define (start_debug)												212
//#define (console_write)											213
//#define (sys_pseudo_fs_get_file_size)								214
#define SYS_DBG_MAT_SET_CONDITION									215
#define SYS_DBG_MAT_GET_CONDITION									216
//#define (logical_console_getc)									217
//#define (logical_console_putc)									218
//#define (logical_console_flush)									219
//#define (get_logical_partition_id)								226
#define SYS_ISOLATED_SPU_CREATE										230	
#define SYS_ISOLATED_SPU_DESTROY									231
#define SYS_ISOLATED_SPU_START										232
#define SYS_ISOLATED_SPU_CREATE_INTERRUPT_TAG						233
#define SYS_ISOLATED_SPU_SET_INT_MASK								234
#define SYS_ISOLATED_SPU_GET_INT_MASK								235
#define SYS_ISOLATED_SPU_SET_INT_STAT								236
#define SYS_ISOLATED_SPU_GET_INT_STAT								237
#define SYS_ISOLATED_SPU_SET_SPU_CFG								238
#define SYS_ISOLATED_SPU_GET_SPU_CFG								239
#define SYS_ISOLATED_SPU_READ_PUINT_MB								240
#define SYS_SPU_THREAD_GROUP_SYSTEM_SET_NEXT_GROUP					244
#define SYS_SPU_THREAD_GROUP_SYSTEM_UNSET_NEXT_GROUP				245
#define SYS_SPU_THREAD_GROUP_SYSTEM_SET_SWITCH_GROUP				246
#define SYS_SPU_THREAD_GROUP_SYSTEM_UNSET_SWITCH_GROUP				247
//#define EMPTY														248
//#define EMPTY														249
#define SYS_SPU_THREAD_GROUP_SET_COOPERATIVE_VICTIMS                250
#define SYS_SPU_THREAD_GROUP_CONNECT_EVENT_ALL_THREADS              251
#define SYS_SPU_THREAD_GROUP_DISCONNECT_EVENT_ALL_THREADS           252
#define SYS_SPU_THREAD_GROUP										253
#define SYS_SPU_THREAD_GROUP_LOG									254
#define SYS_SPU_IMAGE_OPEN_BY_FD                                    260
//#define SYS_PSEUDO_FS_TRUNCATE									295
//#define SYS_PSEUDO_FS_GET_DENTS									296
#define SYS_VM_MEMORY_MAP                                           300
#define SYS_VM_UNMAP                                                301
#define SYS_VM_APPEND_MEMORY                                        302
#define SYS_VM_RETURN_MEMORY                                        303
#define SYS_VM_LOCK                                                 304
#define SYS_VM_UNLOCK                                               305
#define SYS_VM_TOUCH                                                306
#define SYS_VM_FLUSH                                                307
#define SYS_VM_INVALIDATE                                           308
#define SYS_VM_STORE                                                309
#define SYS_VM_SYNC                                                 310
#define SYS_VM_TEST                                                 311
#define SYS_VM_GET_STATISTICS                                       312
#define DIFF_SYS_VM_MEMORY_MAP										313 
//#define EMPTY														314
//#define EMPTY														315
#define SYS_MEMORY_CONTAINER_CREATE                                 324
#define SYS_MEMORY_CONTAINER_DESTROY                                325
#define SYS_MMAPPER_ALLOCATE_FIXED_ADDRESS                          326
#define SYS_MMAPPER_ENABLE_PAGE_FAULT_NOTIFICATION                  327
#define SYS_MMAPPER_ALLOCATE_SHARED_MEMORY_EXT						328 
#define SYS_MMAPPER_FREE_SHARED_MEMORY								329
#define SYS_MMAPPER_ALLOCATE_ADDRESS                                330
#define SYS_MMAPPER_FREE_ADDRESS                                    331
#define SYS_MMAPPER_ALLOCATE_SHARED_MEMORY							332 
#define SYS_MMAPPER_SET_SHARED_MEMORY_FLAG							333
#define SYS_MMAPPER_MAP_SHARED_MEMORY								334
#define SYS_MMAPPER_UNMAP_SHARED_MEMORY								335
#define SYS_MMAPPER_CHANGE_ADDRESS_ACCESS_RIGHT                     336
#define SYS_MMAPPER_SEARCH_AND_MAP                                  337
#define SYS_MMAPPER_GET_SHARED_MEMORY_ATTRIBUTE						338
//#define EMPTY														339
//#define EMPTY														340
#define _SYS_MEMORY_CONTAINER_CREATE								341
#define _SYS_MEMORY_CONTAINER_DESTROY								342
#define SYS_MEMORY_CONTAINER_GET_SIZE                               343
#define SYS_MEMORY_BUDGET_SET										344
//#define EMPTY														345 
//#define EMPTY														346
//#define (sys_mmapper_map_mmio_area)								347
#define SYS_MEMORY_ALLOCATE                                         348
#define SYS_MEMORY_FREE                                             349
#define SYS_MEMORY_ALLOCATE_FROM_CONTAINER                          350
#define SYS_MEMORY_GET_PAGE_ATTRIBUTE                               351
#define SYS_MEMORY_GET_USER_MEMORY_SIZE                             352
#define SYS_MEMORY_GET_USER_MEMORY_STAT								353	
//#define EMPTY														354
//#define EMPTY														355
#define SYS_MEMORY_ALLOCATE_COLORED									356
//#define EMPTY														357
//#define EMPTY														358
//#define (sys_mmapper_unmap_mmio_area)								359
//#define EMPTY														360
#define SYS_MEMORY_ALLOCATE_FROM_CONTAINER_COLORED					361
#define SYS_MMAPPER_ALLOCATE_MEMORY_FROM_CONTAINER					362
//#define EMPTY														363
//#define EMPTY			 											364
#define SYS_UART_INITIALIZE											367	
#define SYS_UART_RECEIVE											368
#define SYS_UART_SEND												369
#define SYS_UART_GET_PARAMS											370
#define SYS_GAME_WATCHDOG_START										372
#define SYS_GAME_WATCHDOG_STOP										373
#define SYS_GAME_WATCHDOG_CLEAR										374
#define SYS_GAME_SET_SYSTEM_SW_VERSION								375
#define SYS_GAME_GET_SYSTEM_SW_VERSION								376
#define SYS_SM_SET_SHOP_MODE										377
#define SYS_SM_GET_EXT_EVENT2					   					378
#define SYS_SM_SHUTDOWN						   					    379
#define SYS_SM_GET_PARAMS					    					380
#define SYS_SM_GET_INTER_LPAR_PARAMETER								381
#define SYS_SM_INITIALIZE											382
#define SYS_GAME_GET_TEMPERATURE									383
#define SYS_SM_GET_TZPB												384
#define SYS_SM_REQUEST_LED											385
#define SYS_SM_CONTROL_LED											386
#define SYS_SM_GET_SYSTEM_INFO										387
#define SYS_SM_RING_BUZZER_TOO										388
#define SYS_SM_SET_FAN_POLICY										389
#define SYS_SM_REQUEST_ERROR_LOG									390
#define SYS_SM_REQUEST_BE_COUNT										391
#define SYS_SM_RING_BUZZER											392
#define SYS_GET_HW_CONFIG					    					393
#define SYS_SM_REQUEST_SCVERSION									394
#define SYS_SM_REQUEST_SYSTEM_EVENT_LOG								395
#define SYS_SM_SET_RTC_ALARM										396
#define SYS_SM_GET_RTC_ALARM										397
#define SYS_CONSOLE_WRITE					    					398
//#define EMPTY 													399
//#define EMPTY 													400
//#define EMPTY 													401
#define SYS_TTY_READ                                                402
#define SYS_TTY_WRITE                                               403
//#define EMPTY														404
//#define EMPTY														405
//#define EMPTY														406
//#define EMPTY														407
#define SYS_SM_GET_TZPB_TOO											408
#define SYS_SM_GET_FAN_POLICY										409
#define SYS_GAME_BOARD_STORAGE_READ									410
#define SYS_GAME_BOARD_STORAGE_WRITE								411
#define SYS_GAME_GET_RTC_STATUS										412
//#define EMPTY														413
//#define EMPTY														414
//#define EMPTY														415
#define SYS_OVERLAY_LOAD_MODULE                                     450
#define SYS_OVERLAY_UNLOAD_MODULE                                   451
#define SYS_OVERLAY_GET_MODULE_LIST                                 452
#define SYS_OVERLAY_GET_MODULE_INFO                                 453
#define SYS_OVERLAY_LOAD_MODULE_BY_FD                               454
#define SYS_OVERLAY_GET_MODULE_INFO2                                455
#define SYS_OVERLAY_GET_SDK_VERSION                                 456
#define _SYS_PRX_GET_MODULE_ID_BY_ADDRESS                           461
#define _SYS_PRX_LOAD_MODULE_BY_FD                                  463
#define _SYS_PRX_LOAD_MODULE_ON_MEMCONTAINER_BY_FD                  464
#define _SYS_PRX_LOAD_MODULE_LIST                                   465
#define _SYS_PRX_LOAD_MODULE_LIST_ON_MEMCONTAINER                   466
#define SYS_PRX_GET_PPU_GUID                                        467
#define _SYS_PRX_LOAD_MODULE                                        480
#define _SYS_PRX_START_MODULE                                       481
#define _SYS_PRX_STOP_MODULE                                        482
#define _SYS_PRX_UNLOAD_MODULE                                      483
#define _SYS_PRX_REGISTER_MODULE                                    484
#define _SYS_PRX_QUERY_MODULE                                       485
#define _SYS_PRX_REGISTER_LIBRARY                                   486
#define _SYS_PRX_UNREGISTER_LIBRARY                                 487
#define _SYS_PRX_LINK_LIBRARY                                       488
#define _SYS_PRX_UNLINK_LIBRARY                                     489
#define _SYS_PRX_QUERY_LIBRARY                                      490
#define SYS_PRX_DBG_GET_MODULE_LIST									492
#define SYS_PRX_DBG_GET_MODULE_INFO									493
#define _SYS_PRX_GET_MODULE_LIST                                    494
#define _SYS_PRX_GET_MODULE_INFO                                    495
#define _SYS_PRX_GET_MODULE_ID_BY_NAME                              496
#define _SYS_PRX_LOAD_MODULE_ON_MEMCONTAINER                        497
#define _SYS_PRX_START                                              498
#define _SYS_PRX_STOP                                               499
#define SYS_HID_MANAGER_OPEN										500
#define SYS_HID_MANAGER_CLOSE										501
#define SYS_HID_MANAGER_READ										502
#define SYS_HID_MANAGER_IOCTL										503
#define SYS_HID_MANAGER_MAP_LOGICAL_ID_TO_PORT_ID					504
#define SYS_HID_MANAGER_UNMAP_LOGICAL_ID_TO_PORT_ID					505
#define SYS_HID_MANAGER_ADD_HOT_KEY_OBSERVER						506
#define SYS_HID_MANAGER_REMOVE_HOT_KEY_OBSERVER						507
#define SYS_HID_MANAGER_GRAB_FOCUS									508
#define SYS_HID_MANAGER_RELEASE_FOCUS								509
#define SYS_HID_MANAGER_CHECK_FOCUS									510
#define SYS_HID_MANAGER_SET_MASTER_PROCESS							511
//#define EMPTY														512
//#define SYS_HID_MANAGER_...										513
//#define SYS_HID_MANAGER_...										514
#define SYS_CONFIG_OPEN												516
#define SYS_CONFIG_CLOSE											517
#define SYS_CONFIG_GET_SERVICE_EVENT								518
#define SYS_CONFIG_ADD_SERVICE_LISTENER								519
#define SYS_CONFIG_REMOVE_SERVICE_LISTENER							520
#define SYS_CONFIG_REGISTER_SERVICE									521
#define SYS_CONFIG_UNREGISTER_SERVICE								522
#define SYS_CONFIG_IO_EVENT											523
#define SYS_CONFIG_REGISTER_IO_ERROR_LISTENER						524
#define SYS_CONFIG_UNREGISTER_IO_ERROR_LISTENER						525
#define SYS_USBD_INITIALIZE											530
#define SYS_USBD_FINALIZE											531
#define SYS_USBD_GET_DEVICE_LIST									532
#define SYS_USBD_GET_DESCRIPTOR_SIZE								533
#define SYS_USBD_GET_DESCRIPTOR										534
#define SYS_USBD_REGISTER_LDD										535
#define SYS_USBD_UNREGISTER_LDD										536
#define SYS_USBD_OPEN_PIPE											537
#define SYS_USBD_OPEN_DEFAULT_PIPE									538
#define SYS_USBD_CLOSE_PIPE											539
#define SYS_USBD_RECEIVE_EVENT										540
#define SYS_USBD_DETECT_EVENT										541
#define SYS_USBD_ATTACH												542
#define SYS_USBD_TRANSFER_DATA										543
#define SYS_USBD_ISOCHRONOUS_TRANSFER_DATA							544
#define SYS_USBD_GET_TRANSFER_STATUS								545
#define SYS_USBD_GET_ISOCHRONOUS_TRANSFER_STATUS					546
#define SYS_USBD_GET_DEVICE_LOCATION								547
#define SYS_USBD_SEND_EVENT											548
#define SYS_USBD_EVENT_PORT_SEND									549
#define SYS_USBD_ALLOCATE_MEMORY									550
#define SYS_USBD_FREE_MEMORY										551
#define SYS_USBD_ENABLE_WAKE_ON										552
//#define EMPTY														553
//#define EMPTY														554
//#define EMPTY														555
#define SYS_USBD_GET_DEVICE_SPEED									556
//#define EMPTY														557
//#define EMPTY														558
#define SYS_USBD_REGISTER_EXTRA_LDD									559
#define SYS_USBMASS_IOCTL											560
//#define EMPTY														561
//#define EMPTY														562
//#define EMPTY														563
//#define EMPTY														564
//#define EMPTY														565
//#define EMPTY														566
//#define EMPTY														567
//#define EMPTY														568
//#define EMPTY														569
#define _YS_PAD_LDD_REGISTER_CONTROLLER								570
#define YS_PAD_LDD_UNREGISTER_CONTROLLER							571
#define YS_PAD_LDD_DATA_INSERT										572
#define YS_PAD_DBG_LDD_SET_DATA_INSERT_MODE							573
#define YS_PAD_LDD_REGISTER_CONTROLLER								574
#define YS_PAD_LDD_GET_PORT_NO										575
#define YS_PAD_MANAGER												577
//#define EMPTY														578
#define YS_BLUETOOTH_AUD_SERIAL_UNK1								579
//#define EMPTY														580
//#define EMPTY														581
//#define EMPTY														582
#define YS_BT_READ_FIRMWARE_VERSION									583
#define YS_BT_COMPLETE_WAKE_ON_HOST									584
#define YS_BT_DISABLE_BLUETOOTH										585
#define YS_BT_ENABLE_BLUETOOTH										586
#define YS_BT_BCCMD													587
#define YS_BT_READ_HQ												588
#define YS_BT_HID_GET_REMOTE_STATUS									589
#define YS_BT_REGISTER_CONTROLLER									590
#define YS_BT_CLEAR_REGISTERED_CONTOLLER							591
#define YS_BT_CONNECT_ACCEPT_CONTROLLER								592
#define YS_BT_GET_LOCAL_BDADDRESS									593
#define YS_BT_HID_GET_DATA											594
#define YS_BT_HID_SET_REPORT										595
#define YS_BT_SCHED_LOG												596
#define YS_BT_CANCEL_CONNECT_ACCEPT_CONTROLLER						597
//#define EMPTY														598
//#define EMPTY														599
#define SYS_STORAGE_OPEN                                            600
#define SYS_STORAGE_CLOSE                                           601
#define SYS_STORAGE_READ                                            602
#define SYS_STORAGE_WRITE                                           603
#define SYS_STORAGE_SEND_DEVICE_COMMAND                             604
#define SYS_STORAGE_ASYNC_CONFIGURE                                 605
#define SYS_STORAGE_ASYNC_READ                                      606
#define SYS_STORAGE_ASYNC_WRITE                                     607
#define SYS_STORAGE_ASYNC_CANCEL                                    608
#define SYS_STORAGE_GET_DEVICE_INFO                                 609
#define SYS_STORAGE_GET_DEVICE_CONFIG                               610
#define SYS_STORAGE_REPORT_DEVICES                                  611
#define SYS_STORAGE_CONFIGURE_MEDIUM_EVENT                          612
#define SYS_STORAGE_SET_MEDIUM_POLLING_INTERVAL                     613
#define SYS_STORAGE_CREATE_REGION                                   614
#define SYS_STORAGE_DELETE_REGION                                   615
#define SYS_STORAGE_EXECUTE_DEVICE_COMMAND                          616
#define SYS_STORAGE_GET_REGION_ACL                                  617
#define SYS_STORAGE_SET_REGION_ACL                                  618
#define SYS_STORAGE_ASYNC_SEND_DEVICE_COMMAND                       619
#define SYS_IO_BUFFER_CREATE                                        624
#define SYS_IO_BUFFER_DESTROY                                       625
#define SYS_IO_BUFFER_ALLOCATE                                      626
#define SYS_IO_BUFFER_FREE                                          627
#define SYS_GPIO_SET                                                630
#define SYS_GPIO_GET                                                631
#define SYS_FSW_CONNECT_EVENT                                       633
#define SYS_FSW_DISCONNECT_EVENT                                    634
//#define EMPTY														635
//#define EMPTY														636
//#define EMPTY														637
//#define EMPTY														638
//#define EMPTY														639
#define SYS_USBBTAUDIO_INITIALIZE									640
#define SYS_USBBTAUDIO_FINALIZE										641
#define SYS_USBBTAUDIO_DISCOVERY									642
#define SYS_USBBTAUDIO_CANCEL_DISCOVERY								643
#define SYS_USBBTAUDIO_PAIRING										644
#define SYS_USBBTAUDIO_SET_PASSKEY									645
#define SYS_USBBTAUDIO_CONNECT										646
#define SYS_USBBTAUDIO_DISCONNECT									647
//#define EMPTY														648
//#define EMPTY														649
#define SYS_RSXAUDIO_INITIALIZE										650
#define SYS_RSXAUDIO_FINALIZE										651
#define SYS_RSXAUDIO_IMPORT_SHARED_MEMORY							652
#define SYS_RSXAUDIO_UNIMPORT_SHARED_MEMORY							653
#define SYS_RSXAUDIO_CREATE_CONNECTION								654
#define SYS_RSXAUDIO_CLOSE_CONNECTION								655
#define SYS_RSXAUDIO_PREPARE_PROCESS								656
#define SYS_RSXAUDIO_START_PROCESS									657
#define SYS_RSXAUDIO_STOP_PROCESS									658
#define SYS_RSXAUDIO_												659
#define SYS_RSX_DEVICE_OPEN                                         666
#define SYS_RSX_DEVICE_CLOSE                                        667
#define SYS_RSX_MEMORY_ALLOCATE                                     668
#define SYS_RSX_MEMORY_FREE                                         669
#define SYS_RSX_CONTEXT_ALLOCATE                                    670
#define SYS_RSX_CONTEXT_FREE                                        671
#define SYS_RSX_CONTEXT_IOMAP                                       672
#define SYS_RSX_CONTEXT_IOUNMAP                                     673
#define SYS_RSX_CONTEXT_ATTRIBUTE                                   674
#define SYS_RSX_DEVICE_MAP                                          675
#define SYS_RSX_DEVICE_UNMAP                                        676
#define SYS_RSX_ATTRIBUTE                                           677
#define SYS_BDEMU_SEND_COMMAND                                      699
#define SYS_NET_ACCEPT						    					700
#define SYS_NET_BIND						    					701
#define SYS_NET_CONNECT						    					702
#define SYS_NET_LISTEN						    					706
#define SYS_NET_RECVFROM					    					707
#define SYS_NET_SENDTO						    					710
#define SYS_NET_SHUTDOWN					    					712
#define SYS_NET_SOCKET						    					713
#define SYS_NET_CLOSE						    					714
#define SYS_NET_BNET_POLL											715
#define SYS_NET_BNET_SELECT											716
#define SYS_NET_OPEN_DUMP											717
#define SYS_NET_READ_DUMP											718
#define SYS_NET_CLOSE_DUMP											719
#define SYS_NET_WRITE_DUMP											720
#define SYS_NET_ABORT												721
#define SYS_NET_INFOCTL												722
#define SYS_NET_CONTROL												723
#define SYS_NET_BNET_IOCTL											724
#define SYS_NET_BNET_SYSCTL											725
#define SYS_NET_EURUS_POST_COMMAND									726
#define SYS_FS_TEST													800
#define SYS_CELLFSOPEN						    					801
#define SYS_CELLFSREAD						    					802
#define SYS_CELLFSWRITE						    					803
#define SYS_CELLFSCLOSE						    					804
#define SYS_CELLFSOPENDIR					    					805
#define SYS_FS_READDIR												806
#define SYS_FS_CLOSEDIR												807
#define SYS_CELLFSSTAT						    					808
#define SYS_CELLFSFSTAT						    					809
#define SYS_FS_LINK													810
#define SYS_CELLFSMKDIR						    					811
#define SYS_CELLFSRENAME                                            812
#define SYS_FS_RMDIR												813
#define SYS_CELLFSUNLINK					    					814
#define SYS_CELLFSUTIME						    					815
#define SYS_FS_ACCESS												816
#define SYS_FS_FCNTL												817
#define SYS_CELLFSLSEEK						    					818
#define SYS_FS_FDATASYNC											819
#define SYS_FS_FSYNC												820
#define SYS_FS_FGET_BLOCK_SIZE										821
#define SYS_FS_GET_BLOCK_SIZE										822
#define SYS_FS_ACL_READ												823
#define SYS_FS_ACL_WRITE											824
#define SYS_FS_LSN_GET_CDA_SIZE										825
#define SYS_FS_LSN_GET_CDA											826
#define SYS_FS_LSN_LOCK												827
#define SYS_FS_LSN_UNLOCK											828
#define SYS_FS_LSN_READ												829
#define SYS_FS_LSN_WRITE											830
#define SYS_FS_TRUNCATE												831
#define SYS_FS_FTRUNCATE											832
#define SYS_FS_SYMBOLIC_LINK										833
#define SYS_FS_CHMOD												834
#define SYS_FS_CHOWN												835
#define SYS_CELLFSNEWFS						    					836
#define SYS_CELLFSMOUNT						    					837
#define SYS_CELLFSUMOUNT					    					838
#define SYS_FS_SYNC													839
#define SYS_FS_DISK_FREE											840
#define SYS_FS_GET_MOUNT_INFO_SIZE									841
#define SYS_FS_GET_MOUNT_INFO										842
#define SYS_FS_GET_FS_INFO_SIZE										843
#define SYS_FS_GET_FS_INFO											844
#define SYS_FS_MAPPED_ALLOCATE										845
#define SYS_FS_MAPPED_FREE											846
#define SYS_FS_TRUNCATE2											847
#define SYSCALL_SYS_SS_GET_CACHE_OF_ANALOG_SUNSET_FLAG				860
#define SYS_SS_PROTECTED_FILE_DB									861
#define SYS_SS_VIRTUAL_TRM_MANAGER									862
#define SYS_SS_UPDATE_MANAGER										863
#define SYS_SS_SEC_HW_FRAMEWORK										864	// storage_manager_if (Interface) auth psx disc: 0x5004, 1. auth ps3 disc: 0x5007, in/out buffer of 0x18 bytes
																		// return to normal : 0x5004, 0x29
#define SYS_SS_RANDOM_NUMBER_GENERATOR								865
#define SYS_SS_SECURE_RTC											866
#define SYS_SS_APPLIANCE_INFO_MANAGER								867
#define SYS_SS_INDIVIDUAL_INFO_MANAGER								868
#define SYS_SS_FACTORY_DATA_MANAGER									869
#define SYS_SS_GET_CONSOLE_ID										870
#define SYS_SS_ACCESS_CONTROL_ENGINE				    			871
#define SYS_SS_GET_OPEN_PSID                                        872
#define SYS_SS_GET_CACHE_OF_PRODUCT_MODE			    			873
#define SYS_SS_GET_CACHE_OF_FLASH_EXT_FLAG			    			874
#define SYS_SS_GET_BOOT_DEVICE					    				875
#define SYS_SS_DISC_ACCESS_CONTROL				    				876
#define SYS_SS_UTOKEN_IF											877
#define SYS_SS_AD_SIGN						    					878
#define SYS_SS_MEDIA_ID						    					879
#define SYS_DECI3_OPEN                                              880
#define SYS_DECI3_CREATE_EVENT_PATH                                 881
#define SYS_DECI3_CLOSE                                             882
#define SYS_DECI3_SEND                                              883
#define SYS_DECI3_RECEIVE                                           884
#define SYS_DECI3_OPEN2												885
//#define EMPTY														889
#define SYS_DECI3_INITIALIZE										890
#define SYS_DECI3_TERMINATE											891
#define SYS_DECI3_DEBUG_MODE										892
#define SYS_DECI3_SHOW_STATUS										893
#define SYS_DECI3_ECHO_TEST											894
#define SYS_DECI3_SEND_DCMP_PACKET									895
#define SYS_DECI3_DUMP_CP_REGISTER									896
#define SYS_DECI3_DUMP_CP_BUFFER									897
#define SYS_DECI3_TEST												899
#define SYS_DBG_STOP_PROCESSES										900
#define SYS_DBG_CONTINUE_PROCESSES									901
#define SYS_DBG_STOP_THREADS										902
#define SYS_DBG_CONTINUE_THREADS									903
#define SYS_DBG_READ_PROCESS_MEMORY									904
#define SYS_DBG_WRITE_PROCESS_MEMORY								905
#define SYS_DBG_READ_THREAD_REGISTER								906
#define SYS_DBG_WRITE_THREAD_REGISTER								907
#define SYS_DBG_GET_PROCESS_LIST									908
#define SYS_DBG_GET_THREAD_LIST										909
#define SYS_DBG_GET_THREAD_INFO										910
#define SYS_DBG_SPU_THREAD_READ_FROM_LS								911
#define SYS_DBG_SPU_THREAD_WRITE_TO_LS								912
#define SYS_DBG_KILL_PROCESS										913
#define SYS_DBG_GET_PROCESS_INFO									914
#define SYS_DBG_SET_RUN_CONTROL_BIT_TO_SPU							915
#define SYS_DBG_SPU_THREAD_GET_EXCEPTION_CAUSE						916
#define SYS_DBG_CREATE_KERNEL_EVENT_QUEUE							917
#define SYS_DBG_READ_KERNEL_EVENT_QUEUE								918
#define SYS_DBG_DESTROY_KERNEL_EVENT_QUEUE							919
#define SYS_DBG_GET_PROCESS_EVENT_CTRL_FLAG							920
#define SYS_DBG_SET_PROCESS_EVENT_CNTL_FLAG							921
#define SYS_DBG_GET_SPU_THREAD_GROUP_EVENT_CNTL_FLAG				922
#define SYS_DBG_SET_SPU_THREAD_GROUP_EVENT_CNTL_FLAG				923
#define SYS_DBG_GET_MODULE_LIST										924
#define SYS_DBG_GET_RAW_SPU_LIST									925
#define SYS_DBG_INITIALIZE_SCRATCH_EXECUTABLE_AREA					926
#define SYS_DBG_TERMINATE_SCRATCH_EXECUTABLE_AREA					927
#define SYS_DBG_INITIALIZE_SCRATCH_DATA_AREA						928
#define SYS_DBG_TERMINATE_SCRATCH_DATA_AREA							929
#define SYS_DBG_GET_USER_MEMORY_STAT								930
#define SYS_DBG_GET_SHARED_MEMORY_ATTRIBUTE_LIST					931
#define SYS_DBG_GET_MUTEX_LIST										932
#define SYS_DBG_GET_MUTEX_INFORMATION								933
#define SYS_DBG_GET_COND_LIST										934
#define SYS_DBG_GET_COND_INFORMATION								935
#define SYS_DBG_GET_RWLOCK_LIST										936
#define SYS_DBG_GET_RWLOCK_INFORMATION								937
#define SYS_DBG_GET_LWMUTEX_LIST									938
#define SYS_DBG_GET_ADDRESS_FROM_DABR								939
#define SYS_DBG_SET_ADDRESS_TO_DABR									940
#define SYS_DBG_GET_LWMUTEX_INFORMATION								941
#define SYS_DBG_GET_EVENT_QUEUE_LIST								942
#define SYS_DBG_GET_EVENT_QUEUE_INFORMATION							943
#define SYS_DBG_INITIALIZE_PPU_EXCEPTION_HANDLER					944
#define SYS_DBG_FINALIZE_PPU_EXCEPTION_HANDLER						945
#define SYS_DBG_GET_SEMAPHORE_LIST									946
#define SYS_DBG_GET_SEMAPHORE_INFORMATION							947
#define SYS_DBG_GET_KERNEL_THREAD_LIST								948
#define SYS_DBG_GET_KERNEL_THREAD_INFO								949
#define SYS_DBG_GET_LWCOND_LIST										950
#define SYS_DBG_GET_LWCOND_INFORMATION								951
#define SYS_DBG_CREATE_SCRATCH_DATA_AREA_EXT						952
#define SYS_DBG_VM_GET_PAGE_INFORMATION								953
#define SYS_DBG_VM_GET_INFO											954
#define SYS_DBG_ENABLE_FLOATING_POINT_ENABLED_EXCEPTION				955
#define SYS_DBG_DISABLE_FLOATING_POINT_ENABLED_EXCEPTION			956
#define SYS_DBG_GET_PROCESS_MEMORY_CONTAINER_INFORMATION			957
//#define SYS_DBG_(send event flags?)								959
#define SYS_CONTROL_PERFORMANCE_MONITOR								960
#define SYS_PERFORMANCE_MONITOR_HIDDEN								961
#define SYS_PERFORMANCE_MONITOR_BOOKMARK							962
#define SYS_LV1_PC_TRACE_CREATE										963
#define SYS_LV1_PC_TRACE_START										964
#define SYS_LV1_PC_TRACE_STOP										965
#define SYS_LV1_PC_TRACE_GET_STATUS									966
#define SYS_LV1_PC_TRACE_DESTROY									967
#define SYS_RSX_TRACE_IOCTL											968
//#define EMPTY 													969
#define SYS_DBG_GET_EVENT_FLAG_LIST									970
#define SYS_DBG_GET_EVENT_FLAG_INFORMATION							971
//#define SYS_DBG_(send event flags?)								972
//#define EMPTY														973
//#define EMPTY														974
#define SYS_DBG_READ_SPU_THREAD_CONTEXT2							975
#define SYS_CRYPTO_ENGINE_CREATE									976
#define SYS_CRYPTO_ENGINE_DESTROY									977
#define SYS_CRYPTO_ENGINE_HASHER_PREPARE							978
#define SYS_CRYPTO_ENGINE_HASHER_RUN								979
#define SYS_CRYPTO_ENGINE_HASHER_GET_HASH							980
#define SYS_CRYPTO_ENGINE_CIPHER_PREPARE							981
#define SYS_CRYPTO_ENGINE_CIPHER_RUN								982
#define SYS_CRYPTO_ENGINE_CIPHER_GET_HASH							983
#define SYS_CRYPTO_ENGINE_RANDOM_GENERATE							984	
#define SYS_DBG_GET_CONSOLE_TYPE									985
//#define EMPTY														986
//#define EMPTY														987
//#define SYS_DBG_(something)_ppu_exception_handler					988	
//#define EMPTY														989

#define MAX_NUM_OF_SYSTEM_CALLS                                    1024

#define LV2_SYSCALL	LV2_CONTEXT

#define LV2_SYSCALL2(ret, name, args) asm("" \
"	.section \".text\"\n" \
"	.align 2\n" \
"	.p2align 3,,7\n" \
"	.globl "#name"\n" \
"	.section \".opd\",\"aw\"\n" \
"	.align 3\n" \
#name": \n" \
"	.quad .L."#name",.TOC.@tocbase\n" \
"	.previous\n" \
"	.type   "#name", @function\n" \
".L."#name":\n" \
"	nop\n" \
"	nop\n" \
"	nop\n" \
"	nop\n" \
"	mflr 0\n" \
"	std 0, 32(1)\n" \
"	std 2, 40(1)\n" \
"	bl +4\n" \
"	li 0, 0\n" \
"	li 2, 0\n" \
"	oris 2, 2, __toc@h\n" \
"	ori 2, 2, __toc@l\n" \
"	oris 0, 0, .L."#name"@h\n" \
"	ori 0, 0, .L."#name"@l\n" \
"	subf 0, 0, 2\n" \
"	mflr 2\n" \
"	addi 2, 2, -32\n" \
"	add  2, 2, 0\n" \
"	bl .L._"#name"\n" \
"	ld 2, 40(1)\n" \
"	ld 0, 32(1)\n" \
"	mtlr 0\n" \
"	blr\n" \
"	.size "#name",.-.L."#name"\n"); \
ret name args; \
ret _##name args

/* Extends the kernel stack of the syscall in 4096 bytes. Can only be called once in a syscall */
LV2_EXPORT int extend_kstack(int unk);

static INLINE uint64_t get_syscall_address(int n)
{
	uint64_t **table = (uint64_t **)MKA(syscall_table_symbol);
	uint64_t *syscall = table[n];
	return syscall[0];
}

static INLINE void create_syscall(int n, void *func)
{
	uint64_t ***table = (uint64_t ***)MKA(syscall_table_symbol);
	uint64_t **syscall = table[n];
	f_desc_t *f = (f_desc_t *)func;	
	syscall[0] = f->addr;	
}

static INLINE void create_syscall2(int n, void *func)
{
	uint64_t **table = (uint64_t **)MKA(syscall_table_symbol);
	f_desc_t *f = (f_desc_t *)func;	
	uint64_t *opd = f->addr;
	
	opd[0] = ((uint64_t)opd) + 16;
	opd[1] = MKA(TOC);
	table[n] = opd;
}

#define patch_syscall	create_syscall

static INLINE void set_syscall_handler(void *syscall_handler)
{
	patch_call(syscall_call_offset, syscall_handler);
}

#endif /* __LV2_SYSCALL_H__ */
