
clean:
	@rm -f *.o *.elf *.self *.484 *.cex *.dex *.bin *.map ../lv1/src/*.o ../debug/src/*.o ../lv2/src/*.o

all:
	@rm -f *.o *.elf *.self *.484 *.cex *.dex *.bin *.484c *.map ../lv1/src/*.o ../debug/src/*.o ../lv2/src/*.o
	@make -f Makefile_484C --no-print-directory

	@rm -f *.o *.elf *.484 *.484d *.cex *.dex *.map ../lv1/src/*.o ../debug/src/*.o ../lv2/src/*.o
	@make -f Makefile_484D --no-print-directory


