
clean:
	@rm -f *.o *.elf *.self *.490 *.cex *.dex *.bin *.map ../lv1/src/*.o ../debug/src/*.o ../lv2/src/*.o

all:
	@rm -f *.o *.elf *.self *.490 *.cex *.dex *.bin *.490c *.map ../lv1/src/*.o ../debug/src/*.o ../lv2/src/*.o
	@make -f Makefile_490C --no-print-directory

	@rm -f *.o *.elf *.490 *.490d *.cex *.dex *.map ../lv1/src/*.o ../debug/src/*.o ../lv2/src/*.o
	@make -f Makefile_490D --no-print-directory


