
clean:
	@rm -f *.o *.elf *.self *.489 *.cex *.dex *.bin *.map ../lv1/src/*.o ../debug/src/*.o ../lv2/src/*.o

all:
	@rm -f *.o *.elf *.self *.489 *.cex *.dex *.bin *.489c *.map ../lv1/src/*.o ../debug/src/*.o ../lv2/src/*.o
	@make -f Makefile_489C --no-print-directory

	@rm -f *.o *.elf *.489 *.489d *.cex *.dex *.map ../lv1/src/*.o ../debug/src/*.o ../lv2/src/*.o
	@make -f Makefile_489D --no-print-directory


