
clean:
	@rm -f *.o *.elf *.self *.491 *.cex *.dex *.bin *.map ../lv1/src/*.o ../debug/src/*.o ../lv2/src/*.o

all:
	@rm -f *.o *.elf *.self *.491 *.cex *.dex *.bin *.491c *.map ../lv1/src/*.o ../debug/src/*.o ../lv2/src/*.o
	@make -f Makefile_491C --no-print-directory

	@rm -f *.o *.elf *.491 *.491d *.cex *.dex *.map ../lv1/src/*.o ../debug/src/*.o ../lv2/src/*.o
	@make -f Makefile_491D --no-print-directory


