
clean:
	@rm -f *.o *.elf *.self *.492 *.cex *.dex *.bin *.map ../lv1/src/*.o ../debug/src/*.o ../lv2/src/*.o

all:
	@rm -f *.o *.elf *.self *.492 *.cex *.dex *.bin *.492c *.map ../lv1/src/*.o ../debug/src/*.o ../lv2/src/*.o
	@make -f Makefile_492C --no-print-directory

	@rm -f *.o *.elf *.492 *.492d *.cex *.dex *.map ../lv1/src/*.o ../debug/src/*.o ../lv2/src/*.o
	@make -f Makefile_492D --no-print-directory


