CFLAGS			= -DPS2GXEMU
TARGET			= ps2gxemu_stage1_file
SRC_SELF		= ../ps2emu_gen/ps2_gxemu.self
OUT_SELF		= ps2_gxemu.self
TEXT_OFFSET		= 0x10000
PAYLOAD_ADDR	= 0x8CAD8
SH_ADDR			= 0x208630
DATA_ADDR		= 0x677880
PATCH_ADDR		= 0x00000000
PATCH_DATA		= 0x00000000

include Makefile.common
