CFLAGS 			= -DPS2HWEMU
TARGET 			= ps2hwemu_stage1_file
SRC_SELF 		= ../ps2emu_gen/ps2_emu.self
OUT_SELF 		= ps2_emu.self
TEXT_OFFSET 	= 0x10000
PAYLOAD_ADDR 	= 0x23CEC
SH_ADDR 		= 0x1BFE68
DATA_ADDR 		= 0x4F78B0
PATCH_ADDR 		= 0xFFFFFFFF
PATCH_DATA 		= 0x00000000

include Makefile.common
